plans:
  - changed-files:
      - any-glob-to-any-file: 'docs/ops/plans/**'
ops:
  - changed-files:
      - any-glob-to-any-file: 'scripts/ops/**'
tooling:
  - changed-files:
      - any-glob-to-any-file: 'scripts/tooling/**'
      - any-glob-to-any-file: 'config/**'
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
backend:
  - changed-files:
      - any-glob-to-any-file: 'apps/backend/**'
frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/frontend/**'
packages:
  - changed-files:
      - any-glob-to-any-file: 'packages/**'
